<h1>Dashboard</h1>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Logout</h3>
			</div>
			<div class="panel-body">
				<p>I want <a href="<?php echo $this->url('logout') ?>">Logout</a></p>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Contents</h3>
			</div>
			<div class="panel-body">
				<p>List of all pages in <a href="<?php echo $this->url('cms')?>">CMS</a> page.</p>
				<p>All <a href="<?php echo $this->url('book')?>">Books</a></p>
			</div>
		</div>
	</div>
</div>
