<?php
$form = $this->form;
$form->setAttribute('action', $this->url('authentication', array('controller' => 'authorize', 'action' => 'index')));
$form->prepare();
?>
<div class="page-header">
	<h1>Authentication</h1>
</div>
<div class="row">
	<div class="col-md-12">
	<?php echo $this->form()->openTag($form); ?>
		<div class="form-group">
			<?php echo $this->formRow($form->get('username')); ?>
		</div>
		<div class="form-group">
			<?php echo $this->formRow($form->get('password')); ?>
		</div>
		<?php echo $this->formSubmit($form->get('submit')); ?>
	<?php echo $this->form()->closeTag(); ?>
	</div>
</div>