<?php $book = $this->book ?>
<div class="page-header">
  <h1>Book: <small><?php echo $book->getTitle(); ?></small></h1>
</div>
<div class="row">
	<div class="col-md-12">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate aliquam repellendus dignissimos voluptates illo maxime distinctio inventore deserunt incidunt. Beatae, vitae voluptates optio ut sed eaque fuga facere eligendi earum!</p>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<ul class="list-group">
		<?php foreach ($book->getPages() as $page) : ?>
		 	<li class="list-group-item">
		  		<a href="<?php echo $this->url('home/page', array('slug' => $page->getUrl())) ?>"><?php echo $page->getTitle() ?></a>
		  	</li>
		<?php endforeach; ?>
		</ul>
	</div>
</div>